### ISSUE TITLE
【Review】プロジェクト要改善事項

### ISSUE THREAD

**Issue by street-m3** [street-m3/corporate-site#22]
## ニュースティッカーをグリッドレイアウトで再現する

**優先度: 低**

### 改善が必要な理由:
ソースコードを見ていると値の変更が加わった時にどの値から変更すれば良いのかがわからない。
改善案: コードの整理(コメントアウトで済む話かもしれない)または、グリッドコンテナーはmax-widthで幅の上限を決め、`grid-rows: auto; grid-template-columns: ..px 1fr ..px;`をイメージしている。

### 作業の範囲:
HTML, CSS, JavaScript

### 補足:
JavaScriptは、ローディングアニメーションが完全に終了したタイミングでニュースティッカー動作させたい。その調整のためにJSが必要となる。
data属性`data-first-visible="true"`の切り替えを行う。

___

- [ ] Completed!😎
<br>
<br>

## 見出しのクラス名を統一させる

**優先度: 低**

### 改善が必要な理由: 
見出しのスタイルは満足しているものの、見出しの使用用途がクラス名を見ただけでは理解できない。ECSS思考のクラス名を付与したいことと、粒度のコントロールが求められる。

### 作業の範囲:
HTML, CSS

___

- [ ] Completed!😎
<br>
<br>

### テーブルのクラス名をより汎用的なものにしたい

**優先度: 中**
    
### 改善が必要な理由: 
①テーブルレイアウトのパターンはおおよそ決まっており、パターン別に決まったクラス名とスタイル(class)を作ってしまえば、今後スムーズな実装ができると考えた。このプロジェクトを機会に作成したい。<br>

②レスポンシブ対応テーブルデザインのパターンは、横or縦スクロールか`<thead>`の位置を変えるなどのパターンが多い。横スクロールを促すJSアニメーションプラグインを用いてすぐに構築できるようにしておいた方がよい。<br>

③ただ、BootstrapやTailwindCSSといったユーティリティファーストのCSSフレームワークは既にデザインパターン(テンプレート)が用意しているのに対して、自分で一から作るとなると手間がかかる。そのため、実際に作るとしたら、3パターンぐらいが妥当と考える。

まずはクラス名を決めてから取り掛かる。
    
### 作業の範囲:
HTML, CSS, VendorJS

___

- [ ] Completed!😎
<br>
<br>

## カルーセルの作成
  
**優先度: 低**

### 改善が必要な理由: 
現在トップページの`p-member`カルーセルは、スクロールバーでスライドさせるタイプで実装している。問題点は、デザインカンプの通に実装ができていないのと、クロスブラウザを完全に網羅できていない。(IE除く)<br>
逆に言えば、JSを用いていないので軽量で作業量が圧倒的に少なく、ユーザーのスクロール操作を促しやすいメリットがある。
<br>
クロスブラウザに対応すること、JSでカルーセルプラグインを準備しておけば今後の制作に役立ちそうなので、改善するとよい。

___

- [ ] Completed!😎
<br>
<br>

### 概要: 
ユーザー投稿記事のテンプレートブロックは、大枠の余白領域を`display: grid;`、コンテンツ領域はコンテナーに格納してレイアウトしている。そもそもGridにする意味と`display: flex;`でレイアウトできないかチェックしたい。

### 改善が必要な理由: 
まず、Gridで作成するのであれば、以下を想定。

```` css
.ly-inner_Grid {
      display: grid;
      grid-template-columns: 40px auto 40px;

    & > * ,
    &::before,
    &::after {
        grid-column: 2;
    }

    &.-xl {
        @media (--xl) {
            grid-template-columns: minmax(40px, 1fr) minmax(auto, $layout-inner-xl) minmax(40px, 1fr);
        }
    }

    &.-lg {
        @media (--lg) {
            grid-template-columns: minmax(40px, 1fr) minmax(auto, $layout-inner-lg) minmax(40px, 1fr);
        }
    }

    &.-sm {
        @media (--sm) {
            grid-template-columns: minmax(40px, 1fr) minmax(auto, $layout-inner-sm) minmax(40px, 1fr);
        }
    }
}

.ly-Article-Scoped.user-Rigting-Area {
    grid-template-rows: clamp(40px, 8.491vw, 116px) auto clamp(58px, 13.762vw, 188px);
    grid-template-columns: minmax(20px, 1fr) minmax(auto, 911px) minmax(20px, 1fr);
    row-gap: 1em;
    background-color: #fff;
}
````

Gridではなく、paddingプロパティで作成するなら、値をそのままコピペすれば良い。

### 作業の範囲:
HTML, CSS

___

- [ ] Completed!😎
<br>
<br>

## 2カラムレイアウト

**優先度: 高**

### 概要:
ブログページをまだ作成していないため。

___

- [ ] Completed!😎
<br>
<br>

### 固定ページのセクションリンク
**優先度: 中**
改善が必要な理由:  `display: flex;`で既に実装済み。ただ、セクションが増えるたびにスタイル調整をするのは、メンテナンス性に欠けるため、Gridレイアウトにしたい。

___

- [ ] Completed!😎
<br>
<br>

## クラス名の変更
  - [ ] パンくずリスト
  - [ ] ページネーション

___

- [ ] Completed!😎
<br>
<br>
