### ISSUE TITLE
【PostCSS】calcで変数計算ができないエラー

### ISSUE THREAD

**Issue by street-m3** [street-m3/corporate-site#6]
## 概要
以下のようなエラーが出る。
内容としては、postcss-calcのバージョンがあげた方が良いということらしい。
あんまり関係ない気がする。別の問題がありそうなので、検討したい。😅

shell
```` shell
Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.9, but postcss-calc uses 7.0.39. Perhaps this is the source of the error below.
JisonLexerError: Lexical error on line 1: Unrecognized text.
````

mixin.pcss
```` css
 @define-mixin lineHeightCrop $line-height {
     &::before {
         content: "";
         display: block;
         width: 0;
         height: 0;
         margin-top: calc((1 - {$line-height}) * .5em);
     }

     &::after {
         content: "";
         display: block;
         width: 0;
         height: 0;
         margin-bottom: calc((1 - {$line-height}) * .5em);
     }
 }

 .sample {
    @add-mixin lineHeightCrop 1.5;
}
````

## 改善案
現在考えている改善案
1. postcss-calcのバージョンをあげてみる。
2. postcss-cssnextも関連しているかもしれないので、postcss-preset-envのインストール。
3. 記述方法が間違っているかもしれないので、調査する。
